ci-host: Lock image to f34, f35 has an issue with Copr deps
python3-copr depends on pyhton3-munch, which is missing a dependency on
python3-setuptools.

Traceback (most recent call last):
  File "/usr/bin/rpm-gitoverlay", line 33, in <module>
    sys.exit(load_entry_point('rpm-gitoverlay==0', 'console_scripts', 'rpm-gitoverlay')())
  File "/usr/lib/python3.10/site-packages/rgo/__main__.py", line 184, in main
    from rgo.builders.copr import CoprBuilder
  File "/usr/lib/python3.10/site-packages/rgo/builders/copr.py", line 21, in <module>
    import copr.v3 as copr
  File "/usr/lib/python3.10/site-packages/copr/v3/__init__.py", line 3, in <module>
    from .helpers import config_from_file
  File "/usr/lib/python3.10/site-packages/copr/v3/helpers.py", line 4, in <module>
    from munch import Munch
  File "/usr/lib/python3.10/site-packages/munch/__init__.py", line 24, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'