Expect /usr/share/dnf5/repos.d in a list of repository configuration paths
<https://github.com/rpm-software-management/libdnf/pull/1783> added
/usr/share/dnf5/repos.d into the default list of repository
configuration paths. That caused failing "Using dnf shell, fail to
install an RPM when no repositories are enabled" test:

  Scenario: Using dnf shell, fail to install an RPM when no repositories are enabled                                                        # dnf/shell-install.feature:22
    When I open dnf shell session                                                                                                           # dnf/steps/shell.py:33
    And I execute in dnf shell "install setup"                                                                                              # dnf/steps/shell.py:48
    Then Transaction is empty                                                                                                               # dnf/steps/transaction.py:255
    And stdout contains "Error: There are no enabled repositories in ".*/etc/yum.repos.d", ".*/etc/yum/repos.d", ".*/etc/distro.repos.d"\." # dnf/steps/cmd.py:237
      Assertion Failed: Stdout doesn't contain: Error: There are no enabled repositories in ".*/etc/yum.repos.d", ".*/etc/yum/repos.d", ".*/etc/distro.repos.d"\.
      Captured stdout:

      Last Command: dnf -y --installroot=/tmp/dnf_ci_installroot_jphacl2c --releasever=29 --setopt=module_platform_id=platform:f29 --disableplugin='*' shell

      Last Command stdout:
      install setup
      Error: There are no enabled repositories in "/tmp/dnf_ci_installroot_jphacl2c/etc/yum.repos.d", "/tmp/dnf_ci_installroot_jphacl2c/etc/yum/repos.d", "/tmp/dnf_ci_installroot_jphacl2c/etc/distro.repos.d", "/tmp/dnf_ci_installroot_jphacl2c/usr/share/dnf5/repos.d".

This patch fixes it.