Use absolute image URL for "eln:latest"
"eln:latest" failed to resolve with podman:

    stdout = 'STEP 1/18: FROM eln:latest'
    stderr = 'Error: creating build container: short-name resolution enforced but cannot prompt without a TTY
	      Error: Failed to build the container.'

The cause is that default
/etc/containers/registries.conf.d/000-shortnames.conf does not map
relative eln name to any registry
<https://github.com/containers/shortnames/issues/71>.

The the image exists at registry.fedoraproject.org/eln:latest,
redirectring to quay.io/fedora/eln:latest.

This fix uses the latter because Fedora is moving to quai.io
<https://forge.fedoraproject.org/infra/tickets/issues/11543>.