Add @not.with_os=rhel__eq__8
This is a quick solution to make ci pass when microdnf tests fail with:
error: (--setopt) Unable to handle: module_platform_id=platform:f29

This will be required in rhel to make the tests pass:
https://github.com/rpm-software-management/microdnf/commit/5621aa58e4cf808e37e91f6a56dcb12c486a65d0

features/module/enable-errors.feature
features/module/install-default.feature
Requires:
https://github.com/rpm-software-management/ci-dnf-stack/pull/923

features/module/remove.feature
Requires:
https://github.com/rpm-software-management/dnf/commit/7d10ddea6291399b3ed794c1d7fff326d2ec3e86

features/plugins-core/reposync.feature
Requires:
https://github.com/rpm-software-management/dnf/commit/01bb29796e926afc4889286513cde638dd8ef625

features/module/add-new-stream-static-context.feature
features/module/enable-contexts.feature
features/module/enable-dependencies.feature
features/module/enable-errors.feature
features/module/install-module-static-context.feature
features/module/platform.feature
Requires:
https://github.com/rpm-software-management/libdnf/pull/1018