Import CA certificates for extra repository files
If extra repositories are located on an HTTPS server with
a certificate signed by a private authority, additional CA
certificates need to be trusted in the container. Otherwise, DNF
invoked in the container will fail to access the repositories:

        STEP 6/15: RUN set -x &&     dnf -y --refresh upgrade;     dnf -y install dnf-plugins-core;     dnf -y copr enable rpmsoftwaremanagement/test-utils;
        + dnf -y --refresh upgrade
        [...]
        Tag repository for rhel-9.6.0-candidate (x86_64 0.0  B/s |   0  B     00:00
        Errors during downloading metadata for repository 'baseos-ci-tag-repository':
          - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://[...]/repodata/repomd.xml [SSL certificate problem: unable to get local issuer certificate]
        Error: Failed to download metadata for repo 'baseos-ci-tag-repository': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried